### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by marcelm** [rhpvorderman/sequali#62]
Sorry, another bug report ...

Sequali version was 0.2.0. The command was just `sequali inputfile.fastq`.

The data is Nanopore reads. I cannot share it, but probably you’ll be able to figure out where the problem is from the stacktrace alone:
```
Traceback (most recent call last):
  File ".../.venv/bin/sequali", line 8, in <module>
    sys.exit(main())
  File ".../.venv/lib/python3.10/site-packages/sequali/__main__.py", line 154, in main
    report_modules = calculate_stats(
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1548, in calculate_stats
    *qc_metrics_modules(metrics, data_ranges),
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1518, in qc_metrics_modules
    PerPositionMeanQualityAndSpread.from_phred_table_and_labels(
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 441, in from_phred_table_and_labels
    accumulated_errors / accumulated_count))
ZeroDivisionError: float division by zero
```

**Comment by rhpvorderman** [comment]
Sure, thanks!
