### ISSUE TITLE
IndexError if a later read was sequenced earlier

### ISSUE THREAD

**Issue by marcelm** [rhpvorderman/sequali#90]
I’m getting another crash, this time it appears to be related to the `start_time` header. This is from a file that contains merged records from two runs. Note that the second start time is earlier than the first:
```
$ cat test.fastq
@r1 runid=1 sampleid=library1 read=1 ch=282 start_time=2022-11-25T14:15:43Z
A
+
#
@r2 runid=2 sampleid=library1 read=1 ch=347 start_time=2022-11-22T14:23:43Z
A
+
#
$ sequali test.fastq
Processing test.fastq: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 164/164 [00:00<00:00, 425kiB/s]
Traceback (most recent call last):
  File ".../.venv/bin/sequali", line 8, in <module>
    sys.exit(main())
  File ".../.venv/lib/python3.10/site-packages/sequali/__main__.py", line 162, in main
    report_modules = calculate_stats(
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1609, in calculate_stats
    NanoStatsReport.from_nanostats(nanostats)
  File ".../.venv/lib/python3.10/site-packages/sequali/report_modules.py", line 1285, in from_nanostats
    time_active_slots_sets[timeslot].add(channel_id)
IndexError: list index out of range
```

**Comment by marcelm** [comment]
CC @ianm0001 who is testing sequali on her data and encountered this problem.

**Comment by rhpvorderman** [comment]
Interesting, I wondered why this bug hasn't been triggered before. The issue is that the start and end time coincided with the timeslot calculation in such a way that the end boundary falls exactly on a timeslot border. Since python arrays go up to but not including the end, it falls in the next slot, but this slot was not present. This only occurs in rare cases. 

I fixed it now. I will release the 0.4.1 patch immediately.

Thanks so much for reporting these bugs and putting up with all the beta issues.

**Comment by rhpvorderman** [comment]
0.4.1 has been released. Wheels should be available shortly. Feel free to report any other issues if they occur. I will fix them ASAP.
